export enum ETranslator {
    NAME = "نام",
    ADDRESS = "آدرس",
    DESCRIPTION = "توضیحات",
    ADD = "اضافه کردن",
    ENTER_NAME ="نام سینما را وارد کنید",
    PARDIS_AND_AMPHITHEATRE = "پردیس و سالن ها",
    PROGRAMS = "برنامه ها",
    TAGS = "برچسب ها",
    SCHADULES = "سانس ها",
    EDIT = "ویرایش",
    SAVE = "ذخیره",
    CANCEL = "انصراف",
    DELETE = "حذف",
    ADD_AMPHITHEATRE = "افزودن سالن",
    AMPHITHEATRE_NAME = "نام سالن",
    ENTER_AMPHITHEATRE_NAME = "نام سالن را وارد کنید",
    NUMBER_OF_FLOOR = "تعداد طبقات",
    ENTER_NUMBER_OF_FLOOR = "تعداد طبقات را وارد کنید",
    NUMBER_OF_CHAIR = "تعداد صندلی",
    ENTER_NUMBER_OF_CHAIR = "تعداد صندلی را وارد کنید",
    UPLOAD_PLAN = "بارگذاری نقشه سالن",
    CINEMA_NAME = "نام سینما"

}